### DISCUSSION TITLE
Introducing a BudgetAdjustment spec

### DISCUSSION THREAD

**Discussion by thisisibrahimd** [OpenSLO/OpenSLO#256] [Ideas]
I would like to introduce a BudgetAdjustment spec to OpenSLO when we need to exclude certain periods of time from the final SLO calculation.

**Comment by fourstepper** [comment]
How would such a spec look like?

Isn't this really application-specific that could perhaps be handled in labels/annotations or something like that?

**Reply by thisisibrahimd** [reply]
Excuse the delay.

The spec would look something like this. Similar to Nobl9's budgetadjustment spec.

```

apiVersion: openslo/v1
kind: BudgetAdjustment
metadata:
  name: string
  displayName: string # optional
  labels:
  annotations:
spec:
  description: string
  indicatorRef: string # SLO Id
  startTime: timestamp # In ISO8601 format
  endTime: timestamp # In ISO8601 format
  timeWindow:
    ## rolling time window
    - duration: duration-shorthand # duration of the window eg 1d, 4w
      isRolling: true
```

I would not consider this something that can be handled in label/annotations as it won't scale nicely.
