### DISCUSSION TITLE
[Proposal] Map SLOs to Entities, not Services

### DISCUSSION THREAD

**Discussion by aaranmcguire** [OpenSLO/OpenSLO#275] [Ideas]
### Context

In the current OpenSLO spec, Service Level Objectives (SLOs) are linked directly to a Service. While this usually works, it becomes problematic for organisations like ours, where a single service may run multiple APIs or components, each with its own set of SLOs.

For example, consider a simple API service with both a public-facing REST endpoint and an internal gRPC endpoint. Each of these endpoints has its own set of SLOs. Mapping these SLOs to a single service complicates visualisation of their impact during incidents and when visualising SLOs in a dependency graphs.

### Proposal

To address this, I propose mapping SLOs to Entities instead of Services. This change allows more flexibility and detailed tracking of SLO compliance for each component. It will help us identify whether an API, database, or other resource is failing its SLOs, rather than blaming a whole service. This approach also aligns better with how many teams currently use [Backstage](https://backstage.io) to manage their software stack.

### Changes

1. **Field Replacement:** Replace the service field in the SLO spec with entityRef, allowing for more flexible and precise mapping. Optionally, an entity field could be included for inline entity definition. Like service, entityRef will be a required field.

1. **Object Type Replacement:** Replace the Service object type with Entity. The Entity object will have a similar structure but will accommodate a broader range of component types.

```
apiVersion: openslo.com/v2alpha1
kind: Entity
metadata:
  name: string
  displayName: string # optional
spec:
  type: string # required, examples: API | Resource | Database | Service | Pipeline
  description: string # optional, up to 1050 characters
```

This change will not only provide more clarity in how SLOs are managed and tracked but will also improve the accuracy and utility of visualisations and dependency graphs. By aligning more closely with existing tools like Backstage, this proposal aims to streamline SLO management and make it more intuitive for teams to implement and maintain.

Feedback welcome.
