### ISSUE TITLE
Make source specification more general

### ISSUE THREAD

**Issue by programmer04** [OpenSLO/OpenSLO#107]
### Problem to solve

Currently, fields for defining data gathering step in YAMLs look like that
```YAML
  source: string # data source for the metric
  queryType: string # a name for the type of query to run on the data source
  query: string # the query to run to return the metric
  metadata: # optional, allows data source specific details to be passed
```
which works nicely for some data sources in which each metric is specified with one string e.g.:
- Prometheus -> `xd_server_requests{code="2xx",host="xd.com"}`
- Datadog -> `avg:trace.http.request.duration{*}`
- Dynatrace -> `builtin:synthetic.http.duration.geo:filter(and(in("dt.entity.http_check",entitySelector("type(http_check),entityName(~"API Sample~")")),in("dt.entity.synthetic_location",entitySelector("type(synthetic_location),entityName(~"N. California~")")))):splitBy("dt.entity.http_check","dt.entity.synthetic_location"):avg:auto:sort(value(avg,descending)):limit(20)` (referenced as `metric selector`)
- Graphite -> `stats.response.200` (referenced as `metric path`)
- Splunk -> `search index=xd-events source=udp:5072 sourcetype=syslog status<400 | bucket _time span=1m | stats avg(response_time) as n9value by _time | rename _time as n9time | fields n9time n9value`
- Splunk Observability -> `"data('demo.trans.latency', filter=filter('demo_datacenter', 'Tokyo') and filter('demo_host', 'server4')).mean().publish()"` (referenced as `program`)
- New Relic -> `SELECT average(duration*1000) FROM Transaction WHERE appName='production' TIMESERIES` 

Even when instead of the `query` this string is referenced differently in data source docs it's quite obvious where to put it in.

But for some other data source to fetch data comfortable you have to specify more e.g.:
- Lightstep -> two values required `XzpycSRa` (referenced as `stream ID`) and `good` (referenced as `type of data`)
- Pingdom -> two values required `5435381` (referenced as `check ID`) and `up` (referenced as `status`)
- App Dynamics -> two values required `xd` (referenced as `application name`) and `End User Experience|App|Very Slow Requests` (referenced as `metricPath`)
- For Redshift, CloudWatch, BigQuery, and other integrations from big cloud providers it may be handy to pass `region`, `project id`, `name of database`, etc.

The above is a little bit hard to describe with our current approach for the schema. It's not flexible enough, I know that whatever can be put in the `metadata` section, but it may not be obvious to use it. What to do with `queryType` and `query` in such a situation?

### Proposal

I'm proposing a flexible approach that can be customizable for each data source vendor, below is the initial draft proposal to discuss.

```YAML
  source: 
    type: string # predefined type e.g. Prometheus, Datadog, etc.
    spec:
        # arbitrary chosen fields for every data source type to make it comfortable to use
```

### Further details

It will make OpenSLO spec flexible for any vendor of metrics
