### ISSUE TITLE
Support Composite SLO in OpenSLO.

### ISSUE THREAD

**Issue by davex98** [OpenSLO/OpenSLO#142]
### Problem to solve

Support Composite SLO in OpenSLO.
The goal of Composite SLO is to enable the user to capture an end-to-end journey.

### Proposal

The Composite SLO will provide users the ability to define an SLO that is based on the health of many independent objectives that are defined with different queries, targets, etc. (even data sources).
 
As an example, the banking industry normally has 10-20 services for a user scenario. Withdrawing money from an ATM requires multiple services and transactions to happen in low latency, high availability environment. The SLO in this case is the success of a customer withdrawing money from an ATM. One might imagine we would aim for 99.99% reliability and with all the underlying services and their SLOs making up the Composite SLO.
 
To enable the creation of a Composite SLO we will have to modify the current structure of our YAML files to enable specifying different SLI for each objective instead of having one SLI for one SLO object. We could achieve that by adding **indicatorRef:**
```yaml
objectives:
  - displayName: string # optional
    op: lte | gte | lt | gt # conditional operator used to compare the SLI against the value. Only needed when using a thresholdMetric
    value: numeric # optional, value used to compare threshold metrics. Only needed when using a thresholdMetric
    target: numeric [0.0, 1.0) # budget target for given objective of the SLO
    timeSliceTarget: numeric (0.0, 1.0] # required only when budgetingMethod is set to TimeSlices
    timeSliceWindow: number | duration-shorthand # required only when budgetingMethod is set to TimeSlices
    indicatorRef: name of the SLI
```

or we could simple inline our SLI in the objective:
```yaml
objectives:
  - displayName: string # optional
    op: lte | gte | lt | gt # conditional operator used to compare the SLI against the value. Only needed when using a thresholdMetric
    value: numeric # optional, value used to compare threshold metrics. Only needed when using a thresholdMetric
    target: numeric [0.0, 1.0) # budget target for given objective of the SLO
    timeSliceTarget: numeric (0.0, 1.0] # required only when budgetingMethod is set to TimeSlices
    timeSliceWindow: number | duration-shorthand # required only when budgetingMethod is set to TimeSlices
    thresholdMetric:
      metricSource: string
        metricSourceRef: string
        spec:
         # arbitrary chosen fields for every data source type to make it comfortable to use

```
### Further details

We could decide on our upcoming community meeting and discuss this way of handling Composite SLO in our standard.
