### ISSUE TITLE
Resolve inconsistency in labels example

### ISSUE THREAD

**Issue by kenfinnigan** [OpenSLO/OpenSLO#143]
### Summary

The label example in the spec uses [this](https://github.com/OpenSLO/OpenSLO#general-schema), but the [definition](https://github.com/OpenSLO/OpenSLO#notes-general-schema) has it as an array of strings and Oslo defines it as [this](https://github.com/OpenSLO/oslo/blob/main/pkg/manifest/v1/objects.go#L92).

We should resolve the inconsistency by updating the example in the spec.

### What is the current *bug* behavior?

Label example uses:

```
metadata:
  name: string
  displayName: string # optional
  labels:
    userImpacting: "true"
    team: "identity"
```

### Possible fixes

Based on the [definition](https://github.com/OpenSLO/OpenSLO#notes-general-schema) the example should be:

```
metadata:
  name: string
  displayName: string # optional
  labels:
    userImpacting:
      - "true"
    team:
      - "identity"
```

**Comment by proffalken** [comment]
I missed this when reviewing the spec - it feels to me that a label should be a key-value pair rather either a string or an array of strings.

Is there a use-case for a label needing to be more than a single value?

In most of the observability solutions that I've used, tags and labels are pretty much always `key: value` and then used to refine data, so I'm not 100% sure what enabling these as arrays gives us?

I'd propose that we update the spec to match the example, not the other way around?

**Comment by kenfinnigan** [comment]
I'm fine with that.

In creating the structs to match the spec I had err'd towards an array of strings as the spec supported a single string or an array of strings, but when defining the struct I didn't think that was possible, and went with the broadest option.

If everyone is good with modifying the spec to support a key with a single value only, it works for me

**Comment by weyert** [comment]
As far as I know it's key-value pairs were the value can either be a string, or an array  of strings?

**Comment by kenfinnigan** [comment]
@weyert how would that be represented in a struct?

**Comment by weyert** [comment]
I imagined something like below:

The YAML listed below:
```yaml
blah: blah
bleh:
  - item1
  - item2
  - item3
```

becomes something like this in JSON:
```json
{
"blah": "blah"
"bleh": ["item1", "item2", "item3"]
}
```

**Comment by proffalken** [comment]
I'm still struggling to understand the use-case here, can you help me out with an example?

The only one I can think of at the moment where an array of strings might be useful would be something around service ownership:

```
metadata:
  name: string
  displayName: string # optional
  labels:
    userImpacting: "true"
    team: "identity"
    owner:
        - team1@myco.com
        - team2@myco.com
        - team3@myco.com
```
but even then I'm not sure this is enough to allow for arrays of strings when the majority of monitoring/observability platforms only allow for simple key/value pairs.
