### ISSUE TITLE
ratioMetric is missing a `raw:` type

### ISSUE THREAD

**Issue by mmazur** [OpenSLO/OpenSLO#154]
`ratioMetric` combines the `good` query or the `bad` query with the `total` query to get a ratio.

Except the ratio itself can already be present as a precalculated metric. Sloth supports this option with a `sli.raw.error_ratio_query` option ([example](https://sloth.dev/examples/default/raw-sli/)).

I'm proposing adding a similar option to `ratioMetric`. Something like:

```
raw: # raw ratio query, either "good/bad" + "total" or "raw" must be provided
  type: success | error  # indicates whether query returns the success or the error ratio
  metricSource:
    (…)
```

(I'm not married to calling it `raw`, so if anybody has better ideas, feel free.)
