### ISSUE TITLE
Support simplified syntax

### ISSUE THREAD

**Issue by mmazur** [OpenSLO/OpenSLO#160]
### Problem to solve

For the purpose of defining a simple SLO both pyrra's and sloth's syntax is much clearer and less verbose. While we can't get to the exact same level of simplicity due to OpenSLO having to support more use cases, we should at least try to get closer than we currently are.

**As a rule, OpenSLO should aim for, whenever possible, adding new features in ways that do not add additional complexity to the simpler use cases.**

### Proposal

With the merging of #155 an SLO target can be defined as `target` using a float 0…1 or a `targetPercent` using the more human-friendly and standard-in-slo-space 0…100. The reason the spec contains both options is to both provide backwards compatibility (`target`) and be more user friendly and match typical user expectations (`targetPercent`).

I propose we take the same approach with other aspects of the spec. I'd like this to be valid OpenSLO *alongside* what's currently in the spec:

```yaml
apiVersion: openslo/v1
kind: SLO
metadata:
  name: shorter-slo
spec:
  indicator:
    spec:
      ratioMetric:
        good:
          query: results{code="good"}
        total:
          query: results{}
  window: 28d
  budgetingMethod: Timeslices
  targetPercent: 99.9
  timeSliceTarget: 0.9
  timeSliceWindow: 5m
```

For comparison the `spec:` portion of this SLO definition is 12 lines in the example above and [19 lines](https://gist.github.com/mmazur/8844e581e592a0d8170354118a578865) in the spec as it currently is.

### Further details

Three changes are proposed, which, per discussion during August's community call, were split into three separate issues:
1. #168
2. #162
3. #169

### Links / references

* This supersedes #145 and addresses the major issue in #150 

#### ~~1. Make `.objectives[].` optional~~

~~It's my guess that the reason `.objectives[].` exist in the way it does was that the initial OpenSLO spec was based on nobl9's experiences with their system and multiple objectives per SLO is something that system supports. And it made sense in that context.~~

~~But the spec evolved beyond that, where nowadays a much more natural definition of multiple SLO targets would be to have a single `SLI` object and then multiple `SLO` objects reference it, with each `SLO` having a single target only.~~

~~Under which scenario `.objectives[].` makes no sense and is just superfluous verbosity. Verbosity which would make using OpenSLO syntax with tools like pyrra or sloth an obviously worse choice compared to their native config formats. Not to mention it makes the current format a bit inconsistent – why is `budgetMethod: Timeslices` outside `.objectives[].`? It'd make just as much sense if it was in, alongside `timeSliceTarget`.~~

~~I also strongly suspect most tools using OpenSLO spec won't consider supporting multiple targets per SLO, and if they do, it'll be using SLIs with multiple SLOs.~~

~~(If we ever make an OpenSLO 2.0 release, the backwards-incompatible dropping of `.objectives[].` would likely be on the list.)~~

#### ~~2. Make `DataSource` optional (#162)~~

~~When `DataSource` was added in PR #111 it was done to increase the flexibility of the spec, unfortunately at the cost of increased verbosity when a user of OpenSLO has no need for that flexibility. With pyrra or sloth the syntax currently would need to be:~~

```yaml
ratioMetric:
  good:
    StringThatDoesntMatterBecauseItsNotUsedForAnythingYetRequired:
      spec:
        query: results{code="good"}
```

~~I'd like to correct that omission by at least partially restoring the original syntax and making it clear that one can use `DataSource` if there's a need for that, otherwise it's fine to just use `good.query` like in the olden days. (There's likely more discussion needed on how to do it properly.)~~

**Comment by proffalken** [comment]
I like the idea behind this, but I'm not 100% convinced that we can do this without dropping the flexibility that we get from OpenSLO vs the other formats you mention.

We love Sloth and are using it in production with our clients, and the lack of support for certain parts of OpenSLO has indeed meant that we have gone with the Sloth native format.

I'm wondering if there's a compromise to be had here by retaining the `dataSource` but moving it down a level and making it optional so we get something like this:

```yaml
apiVersion: openslo/v1
kind: SLO
metadata:
  name: shorter-slo
spec:
  indicator:
    spec:
      ratioMetric:
        good:
            query: results{code="good"}
        DataSource: prometheus  # Optional Field 
        total:
            query: results{}
        DataSource: prometheus  # Optional Field
  budgetingMethod: Timeslices
  targetPercent: 99.9
  timeSliceTarget: 0.9
  timeSliceWindow: 5m
```

I only suggest this because I have a feeling there may be times where our larger customers may want an SLI that pulls the "good" events from one source and the "total" events from another.  Granted, we don't actually have this use-case at the moment, but we do have systems where "success/failure" is logged to a file on disk and yet details of the actual execution of the task are stored in a SQL database.

In this event, we could do something like:

```yaml
apiVersion: openslo/v1
kind: SLO
metadata:
  name: shorter-slo
spec:
  indicator:
    spec:
      ratioMetric:
        good:
            query: SELECT COUNT(id) FROM logs WHERE success == "1" AND system_id == "our_platform";
           dataSource: SQLDB 
        total:
            query: count_over_time({system_id="our_platform"}[1h])
            dataSource: loki
  budgetingMethod: Timeslices
  targetPercent: 99.9
  timeSliceTarget: 0.9
  timeSliceWindow: 5m
```

Sloth, Pyrra, and other tools could then just ignore the `dataSource` for each query because they are focused on a single data storage layer, whereas tools such as [Oslo](https://github.com/openslo/oslo/) or [SloGen](https://github.com/openslo/slogen) would observe the `dataSource` field for each query and act accordingly?
