### ISSUE TITLE
Simplified Syntax: make DataSource use optional

### ISSUE THREAD

**Issue by mmazur** [OpenSLO/OpenSLO#162]
### Problem to solve

The way `metricSource` has been implemented in #111 is:
* inconsistent with how the rest of the spec works:
  * `incidatorRef:` is on the same level as `indicator:`, and yet `metricSourceRef:` is a child of `metricSource:`
  * one can define a fully functional SLI using `SLO.spec.indicator`, but `metricSource:` is something different than `DataSource` (and yet one references a DataSource as **metric**SourceRef)
* needlessly verbose and needlessly incompatible with how things were before (explored in #160).

### Proposal

I don't know how to deal with 1.0 compatibility here, but here's an attempt at a syntax that gives the *optional* ability to utilize DataSources in a way coherent with the rest of the spec.

```yaml
thresholdMetric:
  query: string # optional, the query to run to return the metric; if not present, the
                # provided DataSource object must be sufficient to retrieve the metric
  dataSourceRef: string # optional, name of a defined DataSource objects containing connection details
  dataSource: # optional, an inline definition of a DataSource object
```

### Further details

This is one of the cases implementing suggestions from #160.

**Comment by fpiwowarczyk** [comment]
First of all, good catch with indicator and `indicatorRef` inlined with `indicator`. We should change it.


How about we will go with Kuberentes like approach and use Data Source type as field in yaml. I think it is straight forward and syntax is simpler this way. This also solves problem with different naming conventions in different Data Sources like Lightstep have `streams` or Pingdom has `checkID` and `status` therefore `query` is not always needed.
``` yaml 
    metricSource: 
    # Below fields are mutually exclusive  
      metricSourceRef: string # optional, this field can be used to refer to DataSource object
      cloudWatch: # optional, this field describes arbitrary fields of DataSource 
        ... 
```
 
 DataSource could be changes as well like here:

 ``` yaml 
apiVersion: openslo/v1
kind: DataSource
metadata:
  name: string
  displayName: string # optional
spec:
  cloudWatch:
    accessKeyID: accessKey
    secretAccessKey: secretAccessKey
```


I wonder if we should stay with name DataSource or maybe change it to MetricSource? It might be misleading if we are using it alternately.
