### ISSUE TITLE
Simplified Syntax: support defining a single SLO target without using `.objectives[].`

### ISSUE THREAD

**Issue by mmazur** [OpenSLO/OpenSLO#168]
### Problem to solve

The initial versions of the spec allowed defining multiple targets per SLO by having those targets be elements of a list called `spec.objectives`. With the addition of the SLI object, the preferred way of achieving such an outcome is to define a single SLI object with the metrics and reference it from multiple SLO objects (`spec.indicatorRef`).

This result in the `.objectives[].` list becoming superfluous and a candidate for being superseded by a simpler approach.

### Proposal

Following changes to the spec are proposed:
1. `.objectives[].` list is marked as an optional element of the SLO object to be used for backwards compatibility and for cases where multiple targets per SLO are required (though the suggested implementation of that is using SLI objects).
2. These additions to `SLO.spec` become the preferred way of defining targets:
   ```yaml
   kind: SLO
   spec:
     target: numeric [0.0, 1.0)
     targetPercent: numeric [0.0, 100)
     op: lte | gte | lt | gt
     value: numeric
     timeSliceTarget: numeric (0.0, 1.0]
     timeSliceWindow: number | duration-shorthand
   ```

### Further details

This is one of the cases implementing suggestions from #160.

**Comment by fpiwowarczyk** [comment]
Having multiple objectives is a common scenario during defining SLO therefore I would not suggest to simplify that part of spec. According to literature like [SRE book ](https://sre.google/sre-book/service-level-objectives/)(check _Defining Objectives_) it is recommended to define more than one objective e.g. for internal use have tighter target and looser for external viewers. 

Kuberenetes is also verbose like here e.g [volumes](https://kubernetes.io/docs/concepts/storage/volumes/) always expects list of volumes even if you have only one in most of the cases. 
``` yaml
...
  volumes:
  - name: test-volume
    awsElasticBlockStore:
      volumeID: "<volume id>"
      fsType: ext4
```
