### ISSUE TITLE
Simplified Syntax: move away from the single-item `.timeWindow[]` list

### ISSUE THREAD

**Issue by mmazur** [OpenSLO/OpenSLO#169]
### Problem to solve

The `spec.timeWindow` list of the SLO object accepts only a single item. This means time window options could be provided without using the `timeWindow` list with no loss of functionality.

### Proposal

Following changes to the spec are proposed:

1. The `timeWindow[]` way of doing things is marked as optional, deprecated and to be supported for backwards compatibility only.
2. These additions to SLO.spec become the preferred way of defining time windows:
    ```yaml
    kind: SLO
    spec:
      window: duration-shorthand # assumed a rolling time window unless `calendar` is provided
      calendar: # if provided, the time window is to be treated as calendar-aligned; otherwise defaults to a rolling time window
        startTime: 2020-01-21 12:30:00
        timeZone: Europe/Brzyskorzystewko
    ```

### Further details

This is one of the cases implementing suggestions from #160.
