### ISSUE TITLE
Issue for discussing OpenSLO adoption in Keptn

### ISSUE THREAD

**Issue by vadasambar** [OpenSLO/OpenSLO#187]
### Problem to solve

We are thinking of adopting OpenSLO at Keptn. This issue is for discussing the differences between Keptn SLO/SLI and OpenSLO's SLO/SLI. The end result can be either of: 
1. We have an approach for translating OpenSLO SLO/SLI 's to Keptn's SLO/SLI 's
2. We have a list of TODOs for Keptn and OpenSLO for making the two specs compatible (both in spec and in implementation)
3. We have a list of TODOs for making Keptn's [lighthouse-service](https://github.com/keptn/keptn/tree/master/lighthouse-service) (the component that evaluates SLO) and SLI providers compatible with OpenSLO 

### Proposal
You can find the Keptn proposal for adopting OpenSLO [here](https://github.com/keptn/keptn/discussions/8985) (slide deck [here](https://docs.google.com/presentation/d/1Y_jSgWN6KM578IAJu-eBWtz7kj0c-JTWxS_XRs15uD4/edit#slide=id.p))

### Further details

I think the slide deck and the proposal has more details. 

### Links / references
- [Keptn's SLO specification](https://github.com/keptn/spec/blob/master/service_level_indicator.md)
- [Keptn's SLI specification](https://github.com/keptn/spec/blob/master/service_level_indicator.md)
- [Keptn quality gates](https://keptn.sh/docs/concepts/quality_gates/)
- [Keptn SLI doc](https://keptn.sh/docs/0.19.x/reference/files/sli/)
- [Keptn SLO doc](https://keptn.sh/docs/0.19.x/reference/files/slo/)
- [Keptn official project repo](https://github.com/keptn/keptn)
- [Keptn lighthouse service](https://github.com/keptn/keptn/tree/master/lighthouse-service)
- [Keptn Datadog SLI provider](https://github.com/keptn-sandbox/datadog-service)

**Comment by vadasambar** [comment]
Tried converting Keptn SLO (shortened to KSLO) and to OpenSLO's SLO (shortened to OSLO and pronounced as letters i.e., O-SLO and not as a word like [Oslo](https://en.wikipedia.org/wiki/Oslo)).
KSLO:
```yaml
---
spec_version: '0.1.0'
comparison:
  compare_with: "single_result"
  include_result_with_score: "pass"
  aggregate_function: avg
objectives:
  - sli: http_response_time
    displayName: "HTTP response time"
    pass:
      - criteria:
          - "<0.25" # seconds
    fail:
      - criteria:
          - ">=0.25"

total_score:
  pass: "100%"
```
KSLI:
```yaml
---
spec_version: '1.0'
indicators:
  # http_response_time is the name of the indicator (you can set it to whatever name you like)
  # `avg:network.http.response_time{*} by {$SERVICE}.rollup(avg, $DURATION)` is the query sent to Datadog
  # $SERVICE is the name of the service/url which is hit during the testing phase. datadog-service replaces it with the
  # right value (so that you don't have to do anything)
  # $DURATION is the difference between start and end time of the testing phase. Since the user won't know this 
  # at the time of writing the query, datadog-service provides $DURATION as a placeholder which is replaced later 
  # by datadog-service with the appropriate value 
  http_response_time: avg:network.http.response_time{*} by {$SERVICE}.rollup(avg, $DURATION)
```

OSLO:
```yaml
apiVersion: openslo/v1
kind: SLO
metadata:
  name: "SLO" # KLO doesn't have a notion of SLO name
  displayName: "SLO" 
  annotations:
    # Putting KSLO things which OSLO doesn't support here as annotations
    "keptn/compare_with": "single_result"
    "keptn/include_result_with_score": "pass"
    "keptn/aggregate_function": avg
spec:
  # # name of the service to associate this SLO with, may refer (depends on implementation) to existing object Kind: Service
  # KSLO has something similar but we don't put it in the SLO. We specify it using the `keptn add-resource` e.g., `keptn add-resource --project="podtatohead" --stage="hardening" --service="helloservice" --resource=./quickstart/slo.yaml --resourceUri=slo.yaml` instead
  # `helloservice` is the `service` in OSLO lingo here   
  service: "dummy" 
  # name of the SLI. Required if indicator is not given.
  # we don't use indicatorRef in KSLO  
  # indicatorRef: "dummy" 
  indicator:
    metadata:
      name: http_response_time
      displayName: "HTTP Response Time"
    spec:
      thresholdMetric:
        metricSourceRef: datadog-datasource
        spec:
          # $DURATION and $SERVICE won't work here because they're 
          # injected in at runtime by Keptn SLI provider (datadog SLI provider in this case)
          # query: avg:network.http.response_time{*} by {$SERVICE}.rollup(avg, $DURATION)
          # `dummy` is the service name
          # `2m` because that's the `timeWindow[0].duration` I have provided below
          query: avg:network.http.response_time{*} by dummy.rollup(avg, 2m)
  # this is equivalent to the time duration for evaluating SLO in Keptn
  # except in case of OSLO, we need to specify it on the SLO itself whereas in Keptn this is passed
  # implicitly in the code (we don't write it in the KSLO file) 
  # and substituted in SLI template variables (like $DURATION)
  timeWindow:
    # exactly one item; one of possible: rolling or calendar–aligned time window
    ## rolling time window
    - duration: 2m # duration of the window eg 1d, 4w
      isRolling: true
    # # or
    # ## calendar–aligned time window
    # - duration: duration-shorthand # duration of the window eg 1M, 1Q, 1Y
    # I am assuming the reason we don't have an `endTime` here is because `endTime` is the current time
    # 
    #   calendar:
    #     startTime: 2020-01-21 12:30:00 # date with time in 24h format, format without time zone
    #     timeZone: America/New_York # name as in IANA Time Zone Database
    #   isRolling: false # if omitted assumed `false` if `calendar:` is present
  # this seems to look at the number of favorable occurrences of the events 
  # divided by the total number of events
  # I don't think we support this completely in the KSLO
  budgetingMethod: Occurrences
  # Target is the value we are looking at 
  objectives:
  # http response time should be less than 0.25 seconds
  # for 99.99 percent of time (OSLO doesn't support 100)
  # which I think means OSLO looks at multiple time periods
  # or multiple query results of the SLI and uses
  # `Occurrences` type `budgetingMethod` as specified to
  # calculate the number of favorable occurences (i.e., response time < 0.25 seconds) divided by the total number of occurences.
  - displayName: "http response time"
    target: 0.25
    op: lt
    targetPercent: 99.99


  alertPolicies: # we don't support this in KSLO
```

`datadog` DataSource resource in OpenSLO referred above (we leave implementation of connection to the individual SLI provider integrations in Keptn e.g., look at datadog SLI provider [here](https://github.com/keptn-sandbox/datadog-service/blob/ea66c7484c610ca926a19d5f605187d25fb438e4/helm/templates/secret.yaml#L11-L13))
```yaml
apiVersion: openslo/v1
kind: DataSource
metadata:
  name: datadog-datasource
  displayName: "Datadog Datasource" # optional
spec:
  description: "data source for Datadog" # optional up to 1050 characters
  type: Datadog # predefined type e.g. Prometheus, Datadog, etc.
  connectionDetails:
    # fields used for creating a connection with particular datasource e.g. AccessKeys, SecretKeys, etc.
    # everything that is valid YAML can be put here
    DD_API_KEY: "<datadog-api-key-here>"
    DD_APP_KEY: "<datadog-app-key-here>"
    DD_SITE: "<datadog-site-here>"
```
