### ISSUE TITLE
JSON Schema has invalid references that do not resolve

### ISSUE THREAD

**Issue by dxh9845** [OpenSLO/OpenSLO#241]
### Summary

The JSON schema provided contains references that do not load / resolve. This prevents users from writing schemas with help from JSON / YAML language servers to provide inline-hinting for the schema.

### Steps to reproduce

1. Use VSCode or any other JSON schema compatible editor and write a YAML file with an inline schema definition to the JSON schema:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/OpenSLO/OpenSLO/main/schemas/v1/openslo.schema.json
---
apiVersion: openslo/v1
kind: SLO
metadata:
  name: "cps-api-healthy-requests"
spec:
  service: 
  
```

2. View the VSCode problems section to see the that the schema cannot be loaded from the `openslo.com` hostname:

```
Problems loading reference 'https://openslo.com/schemas/v1/parts/slo-spec.schema.json': Unable to load schema from 'https://openslo.com/schemas/v1/parts/slo-spec.schema.json': Request vscode/content failed unexpectedly without providing any details.
```

### What is the current *bug* behavior?

The OpenSLO schema files are invalid as written and contain `ref`s to subschemas that do not load.

### What is the expected *correct* behavior?

Users should be able to reference the OpenSLO schema and have the references resolve inline such that any valid YAML or JSON Language Server can provide hints on the shape of the OpenSLO schemas.

### Relevant logs and/or screenshots

```
Problems loading reference 'https://openslo.com/schemas/v1/parts/slo-spec.schema.json': Unable to load schema from 'https://openslo.com/schemas/v1/parts/slo-spec.schema.json': Request vscode/content failed unexpectedly without providing any details.
```

<img width="1082" alt="image" src="https://github.com/OpenSLO/OpenSLO/assets/16714180/bb71171d-7088-45b8-8c44-262252b96037">

OpenSLO schema references are not loadable: 
### Possible fixes

Not sure where it is held, but the OpenSLO Github Pages website does not properly resolve the schemas.
