### ISSUE TITLE
RatioMetrics support for single metric

### ISSUE THREAD

**Issue by its02003** [OpenSLO/OpenSLO#28]
In some cases (Dynatrace), ratio metrics are pre-computed by the platform and recording them won't fit with the OpenSLO spec, might it be possible to support a flavor of the Ratiometrics that uses such a value?

Proposed behaviors/format

```yaml
ratioMetrics:
  incremental: true
  rateMetric: true
  good:
    source: <source>
    queryType: <query_type>
    query: '<query>'
    filter: '<filter>' # optional
```

```yaml
ratioMetrics:
  incremental: true
  good:
    source: <source>
    queryType: <query_type>
    query: '<query>'
    filter: '<filter>' # optional
  total:
    source: <source>
    queryType: <query_type>
    query: '<query>'
    filter: '<filter>' // optional
```

This would give the OpenSLO spec compatiblity with the data elements of the [Dynatace SLO implementation](https://www.dynatrace.com/support/help/dynatrace-api/environment-api/service-level-objectives/post-slo/)

**Rate Metric Implementation**
```json
{
  "enabled": true,
  "name": "Payment service availability",
  "customDescription": "Rate of successful payments per week",
  "useRateMetric": true,
  "metricRate": "builtin:service.successes.server.rate",
  "evaluationType": "AGGREGATE",
  "filter": "type(\"HOST\")",
  "target": 95,
  "warning": 97.5,
  "timeframe": "-1d"
}
```

**No Rate Metric Implementation**
```json
{
  "enabled": true,
  "name": "Payment service availability",
  "customDescription": "Rate of successful payments per week",
  "useRateMetric": false,
  "metricNumerator": "builtin:service.errors.server.successCount",
  "metricDenominator": "builtin:service.requestCount.total",
  "evaluationType": "AGGREGATE",
  "filter": "type(\"HOST\")",
  "target": 95,
  "warning": 97.5,
  "timeframe": "-1d"
}
```
