### ISSUE TITLE
Figure out where indicator belongs

### ISSUE THREAD

**Issue by its02003** [OpenSLO/OpenSLO#29]
Right now there seems to be a bit of an identity crisis between ratio based metrics and threshold metrics. To drive more consistency in where each thing is defined, move the data in the spec around

**Current ```thresholdMetric``` Implementation**
```yaml
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: '<slo_1>'
spec:
  description: '<slo_1_description>'
  service: <service_a>
  indicator:
    thresholdMetric:
      source: '<source>'
      query: '<query_1>'
      queryType: '<query_type>'
  timeWindows:
    - unit: <unit>
      count: <numeric>
      isRolling: <boolean>
  budgetingMethod: <method>
  objectives:
    - displayName: <display_name>
      op: <op>
      value: <value>
      target: <target>
```

**Current ```ratioMetric``` Implementation**
```yaml
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: '<slo_1>'
spec:
  description: '<slo_1_description>'
  service: <service_a>
  indicator:
  timeWindows:
    - unit: <unit>
      count: <numeric>
      isRolling: <boolean>
  budgetingMethod: <method>
  objectives:
    - displayName: <display_name>
       value: <value>
       target: <target>
       ratioMetric:
         incremental: <boolean>
         good:
           source: <source>
           queryType: <query>
           query: <query_string>
         total: # the denominator
           source: <source>
           queryType: <query>
           query: <query_string>
```

It would seem easier to manage the spec if the concept of the indicator was either universally handled outside of the objective or inside the objective, not split between them based on the metric type

Having this consistency would drive more universal consistency in SLO definitions.

Choices for implementation might look something like:

(a) **```ratioMetric``` as ```indicator```**
```yaml
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: '<slo_1>'
spec:
  description: '<slo_1_description>'
  service: <service_a>
  indicator:
    ratioMetric:
       incremental: <boolean>
       good:
         source: <source>
         queryType: <query>
         query: <query_string>
       total: # the denominator
         source: <source>
         queryType: <query>
         query: <query_string>
  timeWindows:
    - unit: <unit>
      count: <numeric>
      isRolling: <boolean>
  budgetingMethod: <method>
  objectives:
    - displayName: <display_name>
       value: <value>
       target: <target>
```

**<OR>**

(b) **```indicator``` inside ```objective```**
```yaml
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: '<slo_1>'
spec:
  description: '<slo_1_description>'
  service: <service_a>
  timeWindows:
    - unit: <unit>
      count: <numeric>
      isRolling: <boolean>
  budgetingMethod: <method>
  objectives:
    - displayName: <display_name>
      op: <op>
      value: <value>
      target: <target>
      thresholdMetric:
        source: '<source>'
        query: '<query_1>'
        queryType: '<query_type>'
```

For the record, my vote is option (a) as this properly separates SLI from SLO in the spec
