### ISSUE TITLE
Specify inlined objects shape

### ISSUE THREAD

**Issue by nieomylnieja** [OpenSLO/OpenSLO#308]
# Current state

Currently the OpenSLO specification is quite vague when it comes to defining inlined objects' shape.
For instance, the README.md defines an inlined `AlertCondition` within `AlertPolicy` this:

```yaml
apiVersion: openslo/v1
kind: AlertPolicy
metadata:
  name: AlertPolicy
  displayName: Alert Policy
spec:
  description: Alert policy for cpu usage breaches, notifies on-call devops via email
  alertWhenBreaching: true
  alertWhenResolved: false
  conditions:
    - kind: AlertCondition
      metadata:
        name: cpu-usage-breach
        displayName: CPU Usage breaching
      spec:
        description: SLO burn rate for cpu-usage-breach exceeds 2
        severity: page
        condition:
          kind: burnrate
          op: lte
          threshold: 2
          lookbackWindow: 1h
          alertAfter: 5m
  notificationTargets:
    - targetRef: OnCallDevopsMailNotification
```

On the other hand, an SLO example looks like this:

```yaml
apiVersion: openslo/v1
kind: SLO
metadata:
  name: foo-slo
  displayName: Foo SLO
spec:
  service: foo
  indicator:
    metadata:
      name: foo-error
      displayName: Foo Error
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            metricSourceRef: datadog-datasource
            type: Datadog
            spec:
              query: sum:trace.http.request.hits.by_http_status{http.status_code:200}.as_count()
        total:
          metricSource:
            metricSourceRef: datadog-datasource
            type: Datadog
            spec:
              query: sum:trace.http.request.hits.by_http_status{*}.as_count()
  objectives:
    - displayName: Foo Total Errors
      target: 0.98
```

## The problem

What's the discrepancy here? Well, one contains `kind` and the other does not.
This bears a question, is `kind` required? Why is `apiVersion` not required, or maybe it is?

## Solution

I propose that we describe the expected shape more concretely than just stating a certain object "can be inlined".
I suggest that we remove `kind` entirely, we don't have any polymorphic fields which can contain multiple kinds, the question remains open for `apiVersion`, If we state it's not needed, we should specify that the inlined object's shape must be of the same version as the parent.

**Comment by fourstepper** [comment]
I would, for v2, remove the SLI and AlertCondition objects entirely and use only everything under `spec`

For example:

```
apiVersion: openslo/v1
kind: SLO
metadata:
  name: foo-slo
  displayName: Foo SLO
spec:
  service: foo
  indicator:
    ratioMetric:
      counter: true
      good:
        metricSource:
          metricSourceRef: datadog-datasource
          type: Datadog
          spec:
            query: sum:trace.http.request.hits.by_http_status{http.status_code:200}.as_count()
      total:
        metricSource:
          metricSourceRef: datadog-datasource
          type: Datadog
          spec:
            query: sum:trace.http.request.hits.by_http_status{*}.as_count()
  objectives:
    - displayName: Foo Total Errors
      target: 0.98
```

I would love to get more thoughts from others on this, though. 

@aaranmcguire @fpiwowarczyk @alexewerlof any thoughts here?
