### ISSUE TITLE
Allow defining alerts associated with SLOs

### ISSUE THREAD

**Issue by weyert** [OpenSLO/OpenSLO#37]
### Problem to solve

Typically, when you define a SLO you want to be informed or alerted when they are not met. I would like to be able to define alerts for a SLO.

### Proposal
I would like to propose an enhancement to the SLO specification so that you can associate or link alert definition to the SLO, e.g. 
```
alerts:
  - ./alerts/my-slo-alert.yaml
  - ./alerts/my-slo/alert*.yaml
```

A alert definition for a SLO could be something like:

```yaml
--- 
apiVersion: openslo/v1alpha
description: "A multi-window multi-burn alert is triggered when needed\n"
kind: Alert
metadata: 
  name: HighResponseTime
spec: 
  name: '<slo_1>'
  labels: 
    owner: "shopifiy"
    repo: "shopfiy/shopcart"
    tier: 2
  annotations:
    summary: "Drop in swift responses for Shopcart API"
    displayName: "High response times"
    runbook: https://guide.shopify.com/runbooks/high-response-time
  severity: ticket # severity of the alert (e.g. ticket, page, P1 board meeting request)
  method: simple # define the alert kind, e.g. multi window multi burn
  query: 
    measurement: burnRate # measurement to use
    expression: |  # the query used?
      some_query_for_resource
```

### Further details
None

### Links / references
https://nobl9.github.io/techdocs_YAML_Guide/
