### ISSUE TITLE
Introduce `Bad` as radio-metric value

### ISSUE THREAD

**Issue by geototti21** [OpenSLO/OpenSLO#45]
### Problem to solve
👋 Hey, there are some use-cases where it's easier to measure the `Bad` events of an SLO, e.g. ( Count # of 5xx) instead of the `Good` ones and then do `Total - Bad = Good`. Especially if we want this to be universality used with any kind of datasource.

### Proposal

I recommend to add a `bad` radio-metric value and update the SLO spec that either `good` or `bad` must be set.

``` yaml   
ratioMetrics:
        incremental: true
        bad:
          source: datadog
          queryType: query
          query: sum:requests.error{*}
        total:
          source: datadog
          queryType: query
          query: sum:requests.total{*}
```

Looking forward to your thoughts 😄
