### ISSUE TITLE
Introduce `queryFrequency` to ratioMetric

### ISSUE THREAD

**Issue by geototti21** [OpenSLO/OpenSLO#55]
### Problem to solve

Hey, I'd like to suggest the addition of `queryFrequency` as an optional first-level field to `ratioMetric`. We already have metadata where we can pass extra information but I believe we need this information pretty much to all data sources so I'd like to suggest it be the first level. This is to pass information on how often we want to run the query.

Thoughts on that or how else we can solve this?

### Proposal

```yaml
  objectives:
    - displayName: APILatency
      op: gt
      value: 1
      target: 0.95
      ratioMetric:
        incremental: true
        bad:
          source: MySource
          queryType: query
          queryFrequency: number # integer in seconds, e.g. 60 , 3600
          query: "some query"
        total:
          source: MySource
          queryType: query
          query: "some query"
```
