### ISSUE TITLE
Introduce `annotations` to SLO metadata

### ISSUE THREAD

**Issue by geototti21** [OpenSLO/OpenSLO#57]
### Problem to solve / Proposal

Hey, similar to k8s annotation system, introduce annotations to OpenSLO, where we can pass metadata to OpenSLO implementations. We have a use case where we want to have annotations for Cloudwatch or any kind of metrics publisher, that we would like to set on SLO level. By adding this the Spec is more customizable and by default is not adding any new implementation details.

```yaml
---
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: checkout-front-end-latency
  displayName: Checkout Front End Latency
  annotations:
    paddle.com/cloudwatch-publisher-enabled: true
    paddle.com/cloudwatch-namespace: SLI
```
